import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { supabase } from "@/integrations/supabase/client";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Loader2, Plane, Radio } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { AddressAutocomplete } from "@/components/AddressAutocomplete";

interface Company {
  id: string;
  navn: string;
  org_nummer: string | null;
  adresse: string | null;
  adresse_lat?: number | null;
  adresse_lon?: number | null;
  kontakt_epost: string | null;
  kontakt_telefon: string | null;
  aktiv: boolean;
  selskapstype?: string | null;
}

interface CompanyManagementDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  company: Company | null;
  onSuccess: () => void;
}

const companySchema = z.object({
  navn: z.string()
    .trim()
    .min(1, "Selskapsnavn er påkrevd")
    .max(200, "Selskapsnavn må være under 200 tegn"),
  selskapstype: z.enum(['droneoperator', 'flyselskap']),
  org_nummer: z.string()
    .trim()
    .max(20, "Org.nummer må være under 20 tegn")
    .optional()
    .or(z.literal("")),
  adresse: z.string()
    .trim()
    .max(500, "Adresse må være under 500 tegn")
    .optional()
    .or(z.literal("")),
  adresse_lat: z.number().nullable().optional(),
  adresse_lon: z.number().nullable().optional(),
  kontakt_epost: z.string()
    .trim()
    .email("Ugyldig e-postadresse")
    .max(255, "E-post må være under 255 tegn")
    .optional()
    .or(z.literal("")),
  kontakt_telefon: z.string()
    .trim()
    .max(20, "Telefonnummer må være under 20 tegn")
    .optional()
    .or(z.literal("")),
});

type CompanyFormData = z.infer<typeof companySchema>;

export const CompanyManagementDialog = ({
  open,
  onOpenChange,
  company,
  onSuccess,
}: CompanyManagementDialogProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const isCreating = !company;

  const form = useForm<CompanyFormData>({
    resolver: zodResolver(companySchema),
    defaultValues: {
      navn: "",
      selskapstype: "droneoperator",
      org_nummer: "",
      adresse: "",
      adresse_lat: null,
      adresse_lon: null,
      kontakt_epost: "",
      kontakt_telefon: "",
    },
  });

  useEffect(() => {
    if (open) {
      if (company) {
        form.reset({
          navn: company.navn,
          selskapstype: (company.selskapstype as 'droneoperator' | 'flyselskap') || "droneoperator",
          org_nummer: company.org_nummer || "",
          adresse: company.adresse || "",
          adresse_lat: company.adresse_lat || null,
          adresse_lon: company.adresse_lon || null,
          kontakt_epost: company.kontakt_epost || "",
          kontakt_telefon: company.kontakt_telefon || "",
        });
      } else {
        form.reset({
          navn: "",
          selskapstype: "droneoperator",
          org_nummer: "",
          adresse: "",
          adresse_lat: null,
          adresse_lon: null,
          kontakt_epost: "",
          kontakt_telefon: "",
        });
      }
    }
  }, [open, company, form]);

  const onSubmit = async (data: CompanyFormData) => {
    setIsSubmitting(true);
    
    try {
      const companyData = {
        navn: data.navn,
        selskapstype: data.selskapstype,
        org_nummer: data.org_nummer || null,
        adresse: data.adresse || null,
        adresse_lat: data.adresse_lat || null,
        adresse_lon: data.adresse_lon || null,
        kontakt_epost: data.kontakt_epost || null,
        kontakt_telefon: data.kontakt_telefon || null,
      };

      if (isCreating) {
        // registration_code is auto-generated by trigger
        const { error } = await supabase
          .from("companies")
          .insert(companyData as any);

        if (error) throw error;
        toast.success("Selskap opprettet");
      } else {
        const { error } = await supabase
          .from("companies")
          .update(companyData)
          .eq("id", company.id);

        if (error) throw error;
        toast.success("Selskap oppdatert");
      }

      onSuccess();
      onOpenChange(false);
    } catch (error: any) {
      console.error("Error saving company:", error);
      toast.error("Kunne ikke lagre selskap: " + error.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {isCreating ? "Opprett nytt selskap" : "Rediger selskap"}
          </DialogTitle>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="navn"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Selskapsnavn *</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="Skriv inn selskapsnavn" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="selskapstype"
              render={({ field }) => (
                <FormItem className="space-y-3">
                  <FormLabel>Selskapstype *</FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      value={field.value}
                      className="grid grid-cols-2 gap-4"
                    >
                      <div className="relative">
                        <RadioGroupItem
                          value="droneoperator"
                          id="droneoperator"
                          className="peer sr-only"
                        />
                        <label
                          htmlFor="droneoperator"
                          className="flex flex-col items-center justify-center rounded-md border-2 border-muted bg-popover p-4 hover:bg-accent hover:text-accent-foreground peer-data-[state=checked]:border-primary [&:has([data-state=checked])]:border-primary cursor-pointer"
                        >
                          <Radio className="mb-2 h-6 w-6" />
                          <span className="font-medium">Droneoperatør</span>
                          <span className="text-xs text-muted-foreground mt-1">
                            For droneoperasjoner
                          </span>
                        </label>
                      </div>
                      <div className="relative">
                        <RadioGroupItem
                          value="flyselskap"
                          id="flyselskap"
                          className="peer sr-only"
                        />
                        <label
                          htmlFor="flyselskap"
                          className="flex flex-col items-center justify-center rounded-md border-2 border-muted bg-popover p-4 hover:bg-accent hover:text-accent-foreground peer-data-[state=checked]:border-primary [&:has([data-state=checked])]:border-primary cursor-pointer"
                        >
                          <Plane className="mb-2 h-6 w-6" />
                          <span className="font-medium">Flyselskap</span>
                          <span className="text-xs text-muted-foreground mt-1">
                            For flyoperasjoner
                          </span>
                        </label>
                      </div>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="org_nummer"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Organisasjonsnummer</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="Skriv inn org.nummer" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="adresse"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <AddressAutocomplete
                      label="Adresse"
                      value={field.value || ""}
                      onChange={(val) => {
                        field.onChange(val);
                      }}
                      onSelectLocation={(loc) => {
                        field.onChange(loc.address);
                        form.setValue("adresse_lat", loc.lat);
                        form.setValue("adresse_lon", loc.lon);
                      }}
                      placeholder="Søk etter adresse..."
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="kontakt_epost"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Kontakt e-post</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      type="email"
                      placeholder="kontakt@firma.no"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="kontakt_telefon"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Kontakt telefon</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="+47 123 45 678" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={isSubmitting}
              >
                Avbryt
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {isCreating ? "Opprett" : "Lagre"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};