import type { TourDefinition } from "./types";

export const missionCreationTour: TourDefinition = {
  id: "mission-creation",
  title: "Opprett oppdrag",
  description: "Lær hele arbeidsflyten for å planlegge og fullføre et drone­oppdrag.",
  steps: [
    {
      id: "go-to-missions",
      selector: '[data-tour="mission-create-button"]',
      title: "Start et nytt oppdrag",
      description: "Klikk «Legg til oppdrag» for å starte planleggingen av en ny droneoperasjon.",
      side: "bottom",
      route: "/oppdrag",
    },
    {
      id: "mission-title",
      selector: '[data-tour="mission-title"]',
      title: "Gi oppdraget et tydelig navn",
      description: "Et godt navn gjør det enkelt å gjenfinne og identifisere operasjonen senere.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-customer",
      selector: '[data-tour="mission-customer"]',
      title: "Kunde / prosjekt",
      description: "Knytt oppdraget til en kunde, et prosjekt eller en intern operasjon for sporbarhet og fakturering.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-date",
      selector: '[data-tour="mission-date"]',
      title: "Dato og tid",
      description: "Riktig tidspunkt er viktig for vær, NOTAM, varsling og dokumentasjon.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-location",
      selector: '[data-tour="mission-location"]',
      title: "Sted / posisjon",
      description: "Søk eller velg operasjons­området. Du kan bruke kartet for nøyaktig plassering.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-route-planner",
      selector: '[data-tour="mission-route-planner"]',
      title: "Ruteplanlegger",
      description: "Tegn operasjons­området direkte i kartet. Du kan justere SORA-volum og bufferinnstillinger her.",
      side: "left",
      optional: true,
    },
    {
      id: "mission-buffer-settings",
      selector: '[data-tour="mission-buffer-settings"]',
      title: "SORA-volum og buffer",
      description: "Buffersoner og tilstøtende område beregnes automatisk basert på drone, hastighet og høyde — sentralt for risikovurderingen.",
      side: "right",
      optional: true,
    },
    {
      id: "mission-drone-select",
      selector: '[data-tour="mission-drone-select"]',
      title: "Velg drone",
      description: "Når du velger drone fylles tekniske verdier (vekt, hastighet, høyde) inn automatisk.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-personnel",
      selector: '[data-tour="mission-personnel"]',
      title: "Personell",
      description: "Tildel pilot, observatør og andre roller. Dette dokumenterer ansvar og stillinger under operasjonen.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-equipment",
      selector: '[data-tour="mission-equipment"]',
      title: "Utstyr",
      description: "Knytt batterier og annet utstyr til oppdraget for full sporbarhet.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-risk-assessment",
      selector: '[data-tour="mission-risk-assessment"]',
      title: "Risikovurdering",
      description: "Gjennomgå eller fullfør risikovurderingen før oppdraget godkjennes eller utføres.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-weather-airspace",
      selector: '[data-tour="mission-weather-airspace"]',
      title: "Vær og luftrom",
      description: "Sjekk vær, NOTAM og luftromsstruktur — viktig for operative beslutninger.",
      side: "left",
      optional: true,
    },
    {
      id: "mission-checklist",
      selector: '[data-tour="mission-checklist"]',
      title: "Sjekklister",
      description: "Bruk pre-flight-sjekklistene for trygg og dokumentert utførelse.",
      side: "bottom",
      optional: true,
    },
    {
      id: "mission-save",
      selector: '[data-tour="mission-save"]',
      title: "Lagre oppdraget",
      description: "Lagre lagrer oppdraget som planlagt eller utkast — du kan komme tilbake og redigere når som helst.",
      side: "top",
      optional: true,
    },
    {
      id: "mission-publish",
      selector: '[data-tour="mission-publish"]',
      title: "Publiser / godkjenn",
      description: "Når oppdraget er klart kan det godkjennes eller startes. Godkjenningskravet avhenger av luftrom og selskaps­oppsett.",
      side: "top",
      optional: true,
    },
    {
      id: "mission-safesky",
      selector: '[data-tour="mission-safesky"]',
      title: "SafeSky live",
      description: "Live publisering brukes når du faktisk flyr — husk å avslutte når oppdraget er ferdig.",
      side: "left",
      optional: true,
    },
    {
      id: "mission-flight-logs",
      selector: '[data-tour="mission-flight-logs"]',
      title: "Etterlogging",
      description: "Etter oppdraget kan flylogger importeres og kobles til oppdraget for komplett dokumentasjon.",
      side: "top",
      optional: true,
    },
    {
      id: "mission-incident-report",
      selector: '[data-tour="mission-incident-report"]',
      title: "Hendelser og avvik",
      description: "Rapporter observasjoner, avvik eller hendelser knyttet til oppdraget når det er relevant.",
      side: "top",
      optional: true,
    },
    {
      id: "finish",
      selector: '[data-tour="mission-create-button"]',
      title: "Du har sett oppdragsflyten",
      description: "Du kan starte denne guiden på nytt når som helst fra Min profil → Kompetanse, eller hjelp-knappen i toppen.",
      side: "bottom",
      route: "/oppdrag",
      optional: true,
    },
  ],
};
