import type { TourDefinition } from "./types";
import { openMobileNavIfNeeded, closeMobileNav } from "./tourUtils";

export const systemOverviewTour: TourDefinition = {
  id: "system-overview",
  title: "Systemoversikt",
  description: "Bli kjent med hovedmenyen og modulene i AviSafe.",
  steps: [
    {
      id: "intro",
      selector: 'header',
      title: "Velkommen til AviSafe",
      description: "Vi tar deg gjennom hovedmenyen så du vet hvor alt ligger. Bruk Neste, Tilbake eller Hopp over når som helst.",
      side: "bottom",
      beforeStep: closeMobileNav,
    },
    {
      id: "nav-missions",
      selector: '[data-tour="nav-missions"]',
      title: "Oppdrag",
      description: "Planlegg, kjør og dokumenter alle drone­operasjoner her. Dette er hjertet av arbeidsflyten.",
      side: "bottom",
      requiresModule: "missions",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-map",
      selector: '[data-tour="nav-map"]',
      title: "Kart",
      description: "Se luftrom, NOTAM, vær og planlegg ruter. Brukes ved planlegging og operativ vurdering.",
      side: "bottom",
      requiresModule: "map",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-documents",
      selector: '[data-tour="nav-documents"]',
      title: "Dokumenter",
      description: "Felles dokumentbibliotek for prosedyrer, manualer og rapporter.",
      side: "bottom",
      requiresModule: "documents",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-calendar",
      selector: '[data-tour="nav-calendar"]',
      title: "Kalender",
      description: "Få oversikt over planlagte oppdrag og tidsplanlegging.",
      side: "bottom",
      requiresModule: "calendar",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-incidents",
      selector: '[data-tour="nav-incidents"]',
      title: "Hendelser",
      description: "Rapporter avvik, observasjoner og hendelser. Viktig for kontinuerlig sikkerhet.",
      side: "bottom",
      requiresModule: "incidents",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-status",
      selector: '[data-tour="nav-status"]',
      title: "Status",
      description: "Operativ status for selskapet — pågående flyvninger og varsler.",
      side: "bottom",
      requiresModule: "status",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-resources",
      selector: '[data-tour="nav-resources"]',
      title: "Ressurser",
      description: "Droner, batterier, utstyr, vedlikehold, personell og kompetanse.",
      side: "bottom",
      requiresModule: "resources",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-changelog",
      selector: '[data-tour="nav-changelog"]',
      title: "Driftstatus",
      description: "Se endringslogg og driftsmeldinger for plattformen.",
      side: "bottom",
      optional: true,
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-admin",
      selector: '[data-tour="nav-admin"]',
      title: "Administrasjon",
      description: "Selskapsinnstillinger, brukerstyring og integrasjoner. Kun synlig for administratorer.",
      side: "bottom",
      requiresAdmin: true,
      beforeStep: closeMobileNav,
    },
    {
      id: "nav-profile",
      selector: '[data-tour="nav-profile"]',
      title: "Min profil",
      description: "Personlige opplysninger, sikkerhet, kompetanse og varslinger. Du kan starte denne guiden igjen herfra.",
      side: "bottom",
      beforeStep: closeMobileNav,
    },
    {
      id: "finish",
      selector: 'header',
      title: "Det var hovedmenyen!",
      description: "Du finner alle modulene fra toppen. Tips: Start guiden «Opprett oppdrag» når du er klar for å lære oppdragsflyten.",
      side: "bottom",
      beforeStep: closeMobileNav,
    },
  ],
};
