import type { TFunction } from "i18next";
import type { TourDefinition } from "./types";
import { openMobileNavIfNeeded, closeMobileNav } from "./tourUtils";

export const createSystemOverviewTour = (t: TFunction): TourDefinition => ({
  id: "system-overview",
  title: t("tours.systemOverview.title"),
  description: t("tours.systemOverview.description"),
  steps: [
    {
      id: "intro",
      selector: 'header',
      title: t("tours.systemOverview.steps.intro.title"),
      description: t("tours.systemOverview.steps.intro.description"),
      side: "bottom",
      beforeStep: closeMobileNav,
    },
    {
      id: "nav-missions",
      selector: '[data-tour="nav-missions"]',
      title: t("tours.systemOverview.steps.nav-missions.title"),
      description: t("tours.systemOverview.steps.nav-missions.description"),
      side: "bottom",
      requiresModule: "missions",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-map",
      selector: '[data-tour="nav-map"]',
      title: t("tours.systemOverview.steps.nav-map.title"),
      description: t("tours.systemOverview.steps.nav-map.description"),
      side: "bottom",
      requiresModule: "map",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-documents",
      selector: '[data-tour="nav-documents"]',
      title: t("tours.systemOverview.steps.nav-documents.title"),
      description: t("tours.systemOverview.steps.nav-documents.description"),
      side: "bottom",
      requiresModule: "documents",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-calendar",
      selector: '[data-tour="nav-calendar"]',
      title: t("tours.systemOverview.steps.nav-calendar.title"),
      description: t("tours.systemOverview.steps.nav-calendar.description"),
      side: "bottom",
      requiresModule: "calendar",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-incidents",
      selector: '[data-tour="nav-incidents"]',
      title: t("tours.systemOverview.steps.nav-incidents.title"),
      description: t("tours.systemOverview.steps.nav-incidents.description"),
      side: "bottom",
      requiresModule: "incidents",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-status",
      selector: '[data-tour="nav-status"]',
      title: t("tours.systemOverview.steps.nav-status.title"),
      description: t("tours.systemOverview.steps.nav-status.description"),
      side: "bottom",
      requiresModule: "status",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-resources",
      selector: '[data-tour="nav-resources"]',
      title: t("tours.systemOverview.steps.nav-resources.title"),
      description: t("tours.systemOverview.steps.nav-resources.description"),
      side: "bottom",
      requiresModule: "resources",
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-changelog",
      selector: '[data-tour="nav-changelog"]',
      title: t("tours.systemOverview.steps.nav-changelog.title"),
      description: t("tours.systemOverview.steps.nav-changelog.description"),
      side: "bottom",
      optional: true,
      beforeStep: openMobileNavIfNeeded,
    },
    {
      id: "nav-admin",
      selector: '[data-tour="nav-admin"]',
      title: t("tours.systemOverview.steps.nav-admin.title"),
      description: t("tours.systemOverview.steps.nav-admin.description"),
      side: "bottom",
      requiresAdmin: true,
      beforeStep: closeMobileNav,
    },
    {
      id: "nav-profile",
      selector: '[data-tour="nav-profile"]',
      title: t("tours.systemOverview.steps.nav-profile.title"),
      description: t("tours.systemOverview.steps.nav-profile.description"),
      side: "bottom",
      beforeStep: closeMobileNav,
    },
    {
      id: "finish",
      selector: 'header',
      title: t("tours.systemOverview.steps.finish.title"),
      description: t("tours.systemOverview.steps.finish.description"),
      side: "bottom",
      beforeStep: closeMobileNav,
    },
  ],
});
