// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-missions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_missions_default = defineTool2({
  name: "list_missions",
  title: "List missions",
  description: "List the signed-in user's visible drone missions (oppdrag), most recent first. Respects company/department visibility via RLS.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Maximum number of missions to return (1-100)."),
    status: z2.string().optional().describe("Optional approval_status filter (e.g. 'pending', 'approved').")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("missions").select("id, lokasjon, beskrivelse, approval_status, company_id, latitude, longitude").order("id", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("approval_status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { missions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-mission.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_mission_default = defineTool3({
  name: "get_mission",
  title: "Get mission",
  description: "Fetch a single mission (oppdrag) by id. Respects RLS visibility for the signed-in user.",
  inputSchema: {
    id: z3.string().uuid().describe("Mission UUID.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("missions").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Mission not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { mission: data }
    };
  }
});

// src/lib/mcp/tools/list-incidents.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_incidents_default = defineTool4({
  name: "list_incidents",
  title: "List incidents",
  description: "List the signed-in user's visible incidents (hendelser), most recent first. Respects company/department visibility via RLS.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(20).describe("Maximum number of incidents to return (1-100)."),
    severity: z4.string().optional().describe("Optional alvorlighetsgrad filter (e.g. 'lav', 'medium', 'hoy').")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, severity }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("incidents").select(
      "id, tittel, beskrivelse, alvorlighetsgrad, status, kategori, hendelsestidspunkt, lokasjon, incident_number"
    ).order("hendelsestidspunkt", { ascending: false }).limit(limit ?? 20);
    if (severity) q = q.eq("alvorlighetsgrad", severity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { incidents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-drones.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_drones_default = defineTool5({
  name: "list_drones",
  title: "List drones",
  description: "List the signed-in user's visible drones. Respects company/department visibility via RLS.",
  inputSchema: {
    limit: z5.number().int().min(1).max(200).default(50).describe("Maximum number of drones to return (1-200).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("drones").select("*").limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { drones: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pmucsvrypogtttrajqxq";
var mcp_default = defineMcp({
  name: "avisafe-mcp",
  title: "AviSafe",
  version: "0.1.0",
  instructions: "Tools for AviSafe \u2014 the safety management system for drone operations. Use `list_missions` and `get_mission` to inspect oppdrag, `list_incidents` for hendelser, and `list_drones` for the drone fleet. All tools return data scoped to the signed-in user's company/department visibility via RLS. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_missions_default, get_mission_default, list_incidents_default, list_drones_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
